### ISSUE TITLE
How do you rotate a primitive?

### ISSUE THREAD

**Issue by mitchellwrosen** [sbidin/sdl2-gfx#5]
Hello! I'm trying to learn sdl-gfx via these bindings and I'm having difficulty combining primitives with rotozoom.

In the C library, the primitives take an `SDL_Surface*`, but here, they take a `Renderer`. How then are you meant to, say, rotate a polygon? Thanks.

**Comment by sbidin** [comment]
> In the C library, the primitives take an `SDL_Surface*`

Are you sure? Here's the [documentation](http://www.ferzkopp.net/Software/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives_8h.html), they all take a renderer. You might be looking at the SDL1, not the SDL2 version?

> How then are you meant to, say, rotate a polygon?

You can draw a polygon to a surface, then rotate the entire surface. Then draw the resulting new rotated surface to the screen. I believe SDL itself provides a way to create a renderer from a surface.

**Comment by mitchellwrosen** [comment]
> Are you sure? Here's the documentation, they all take a renderer. You might be looking at the SDL1, not the SDL2 version?

Oops.. yep! SDL 1.

> I believe SDL itself provides a way to create a renderer from a surface.

Good to know, I'll hunt around!

**Comment by mitchellwrosen** [comment]
`SDL_CreateSoftwareRenderer` :)
